server: 
  port: 9002
  
spring:
  application: 
    name: turbine

eureka: 
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  healthcheck:
     enabled: false
  instance:
    lease-renewal-interval-in-seconds: 10 #租期更新时间间隔R（默认30秒）
    lease-expiration-duration-in-seconds: 30  #租期到期时间（默认90秒）
    metadata-map:
      cluster: main
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    
turbine:
  app-config: mg-user-core, mg-sop, mg-sociality-core
#  app-config: MIGUINTERFACE,MIGUDEMOCORE,MIGU_ZUUL,SPRING_CLOUD_EUREKA   ##需要监控的服务名
#  aggregator: 
#    clusterConfig: main ##需要监控的服务集群名
  aggregator:
    clusterConfig: jiqun1
  cluster-name-expression: new String("jiqun1")
  combine-host-port: true