server:
  port: 9001

spring:
#  profiles:
#    active: local
  application:
    name: nacos-provider
  security:
    user:
      name: yugj
      password: yugj
      roles: sys
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /sys
  health:
    NacosDiscovery:
      enabled: false
    NacosConfig:
      enabled: false
sys.useNacosAfterStoppedEvent: true