server:
  port: 9008

spring:
  profiles:
    active: @profile.id@
  application:
    name: rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# not working
#    listener:
#      simple:
#        missing-queues-fatal: false
#      direct:
#        missing-queues-fatal: false