server:
  port: 9006

spring:
  profiles:
    active: local
  application:
    name: rest-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    initial-instance-info-replication-interval-seconds: 500 #default 40 not working
    registry-fetch-interval-seconds: 5
  healthcheck:
     enabled: true
  instance:
    lease-renewal-interval-in-seconds: 5 #租期更新时间间隔R（默认30秒）
    lease-expiration-duration-in-seconds: 15  #租期到期时间（默认90秒）
    metadata-map:
      cluster: main
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
management:
  security:
    enabled: false
endpoints:
  shutdown:
    enabled: true
    sensitive: false
log:
  home: /data/logs/${spring.profiles.active}

sys:
  eureka:
    shuntDownWaitSeconds: 1