server:
  port: 9007

spring:
  application:
    name: sv-hystrix

# feign中启用Hystrix
feign:
  hystrix:
    enabled: true
#熔断器超时时间设置
hystrix:
  threadpool:
    default:
      coreSize: 10
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
      circuitBreaker:
        requestVolumeThreshold: 2
    "HellStub2#hell2(HellReq)":
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
      circuitBreaker:
        requestVolumeThreshold: 2
    "hystrix-rest":
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
      circuitBreaker:
        requestVolumeThreshold: 2
    "rest-serv":
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
      circuitBreaker:
        requestVolumeThreshold: 2
ribbon:
  MaxConnectionsPerHost: 1000
  MaxTotalConnections: 3000
  ReadTimeout: 2000
  ConnectTimeout: 100
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  ServerListRefreshInterval: 5000
"HellStub2#hell2(HellReq)":
  ribbon:
    MaxConnectionsPerHost: 1000
    MaxTotalConnections: 3000
    ReadTimeout: 20000
    ConnectTimeout: 10000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  healthcheck:
     enabled: false
  instance:
    lease-renewal-interval-in-seconds: 5 #租期更新时间间隔R（默认30秒）
    lease-expiration-duration-in-seconds: 15  #租期到期时间（默认90秒）
    registry-fetch-interval-seconds: 5 #更新eureka时间 默认30秒
    metadata-map:
      cluster: main
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}