server:
  port: 9010

spring:
  application:
    name: sv-ribbon
ribbon:
  MaxConnectionsPerHost: 1000
  MaxTotalConnections: 3000
  ReadTimeout: 10000
  ConnectTimeout: 2000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  ServerListRefreshInterval: 5000
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.AvailabilityFilteringRule
  eureka:
    enabled: true
#ribbon without eureka
justribbon:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    NFLoadBalancerPingClassName: indi.yugj.test.springcloud.ribbon.CustomPing4Ribbon
    listOfServers: http://localhost:9006,http://localhost:9106
    eureka:
      enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    registry-fetch-interval-seconds: 5 #更新eureka时间 默认30秒
  healthcheck:
     enabled: true
  instance:
    lease-renewal-interval-in-seconds: 5 #租期更新时间间隔R（默认30秒）
    lease-expiration-duration-in-seconds: 15  #租期到期时间（默认90秒)
    metadata-map:
      cluster: main
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}