server:
  port: 9015

spring:
  profiles:
    active: local
  application:
    name: stream
  cloud:
    stream:
      bindings:
        #default bindings
#        input:
#          destination: ex.stream
#        output:
#          destination: ex.stream
#          contentType: application/json
        # my test channel bindings
        inputHell:
          destination: ex.bizRouter
        outputHell:
          destination: ex.bizRouter
          contentType: application/json
      rabbit:
        bindings:
          inputHell:
            consumer:
              bindingRoutingKey: q.hell.yugj
          outputHell:
            producer:
              routing-key-expression: '''q.hell.yugj'''
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  security:
    enabled: false
endpoints:
  shutdown:
    enabled: true
    sensitive: false