server:
  port: 9015

spring:
  profiles:
    active: local
  application:
    name: stream
  cloud:
    stream:
      bindings:
        input:
          destination: q.hell.stream
        output:
          destination: q.hell.stream
          contentType: application/json
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  security:
    enabled: false
endpoints:
  shutdown:
    enabled: true
    sensitive: false